### ISSUE TITLE
compiled

### ISSUE THREAD

**Issue by Cryptowater** [PillSniper/PillSniper-Solana-and-Pump-PumpFun-Sniper-Bot#3]
Hi, I tried to use the compile version but every time I open it my browser get closed and nothing else happens

**Comment by PillSniper** [comment]
Hello, we updated the source code, try now!

**Comment by Cryptowater** [comment]
Have you got the telegram version as well? Because I've seen one with your
software name on it

**Comment by PillSniper** [comment]
No that is a scam
